services:
  kuke-board-mysql:
    image: mysql:8.0.38
    container_name: kuke-board-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./kuke-board:/var/lib/mysql
  kuke-board-redis:
    image: redis:7.4
    container_name: kuke-board-redis
    ports:
      - "6379:6379"
    volumes:
      - ./kuke-redis:/data
  kuke-board-kafka:
    image: apache/kafka:3.8.0
    container_name: kuke-board-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # 👇 반드시 CONTROLLER 리스너를 포함해야 함
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
